Charity/Controllers/ACNCController.cs
using BuisnessEntities.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BuisnessEntities.Concrete;
using DCCA.Controllers;

namespace Charity.Controllers
{
    public class ACNCController : BaseController
    {
       
        public ACNCController() : base()
        {
            
        }
        // GET: ACNC
        public ActionResult GetACNCDetails(FilterCriteriaModel criteria)
        {
            var result = new ACNCRepository().GetListOfACNCDetails(criteria);
            string view = RenderRazorViewToString("_LoadResults", result.DataList);
            result.Data = view;
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCareFor()
        {
            var result = new ACNCRepository().GetCareFor().ToList();
            string view = RenderRazorViewToString("_CareFor", result);
            return Json(new ActionOutput<string>{
                Object = view,
                Status = BuisnessEntities.Entities.ActionStatus.Successfull
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetHelpFor(int CareForId)
        {
            var result = new ACNCRepository().GetHelpFor(CareForId);
            string view = RenderRazorViewToString("_HelpForData", result);
            return Json(new ActionOutput<string>
            {
                Object = view,
                Status = BuisnessEntities.Entities.ActionStatus.Successfull
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetFacilities(int HelpForId)
        {
            var result = new ACNCRepository().GetFacility(HelpForId);
            string view = RenderRazorViewToString("_Facilities", result);
            return Json(new ActionOutput<string>
            {
                Object = view,
                Status = BuisnessEntities.Entities.ActionStatus.Successfull
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Volunteer()
        {
            try
            {
                string CountOldPeopleList = string.Empty;
                string InYearList = string.Empty;
                string CountChildAssistance = string.Empty;
                string CAssistanceYearList = string.Empty;
                string ChildCareList = string.Empty;
                string CountDisabilityAssistance = string.Empty;
                string DAssistanceYearList = string.Empty;
                string CountEngSpeak = string.Empty;
                string EngIssue = string.Empty;

                new ACNCRepository().GetListOfOldPeople(out  CountOldPeopleList, out InYearList);
                ViewBag.PeopleCount_List = CountOldPeopleList.Trim();
                ViewBag.Year_List = InYearList.Trim();

                new ACNCRepository().GetChildCareAssistance(out CountChildAssistance, out CAssistanceYearList);
                ViewBag.CountChildAssistance_List = CountChildAssistance.Trim();
                ViewBag.CAssistanceYear_List = CAssistanceYearList.Trim();
                

                new ACNCRepository().GetDisabilityAssistance(out CountDisabilityAssistance, out DAssistanceYearList);
                ViewBag.CountDisabilityAssistance_List = CountDisabilityAssistance.Trim();
                ViewBag.DAssistanceYear_List = DAssistanceYearList.Trim();

                new ACNCRepository().GetSpokenEnglish(out CountEngSpeak,out InYearList);
                ViewBag.CountEngSpeak_List = CountEngSpeak.Trim();
                ViewBag.EngIssue_List = EngIssue.Trim();

                return View();
            }
            catch (Exception)
            {
                throw;
            }
        }

        public ActionResult SearchForACNCDetails(FilterCriteriaModel filter)
        {
            var result = new ACNCRepository().SearchACNCDetails(filter);
            string view = RenderRazorViewToString("_LoadResults", result.DataList);
            result.Data = view;
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult IssuesInGE()   
        {
            try
            {
                string CountOldPeopleList = string.Empty;
                string InYearList = string.Empty;
                string CountChildAssistance = string.Empty;
                string CAssistanceYearList = string.Empty;
                string CChildCare_List = string.Empty;
                string CountDisabilityAssistance = string.Empty;
                string DAssistanceYearList = string.Empty;
                string CountEngSpeak = string.Empty;
                string EngIssue_Year = string.Empty;
                string CountEducation = string.Empty;
                string Education_Year = string.Empty;

                new ACNCRepository().GetListOfOldPeople(out CountOldPeopleList, out InYearList);
                ViewBag.PeopleCount_List = CountOldPeopleList.Trim();
                ViewBag.Year_List = InYearList.Trim();

                new ACNCRepository().GetChildCareAssistance(out CountChildAssistance, out CAssistanceYearList);
                ViewBag.CountChildAssistance_List = CountChildAssistance.Trim();
                ViewBag.CAssistanceYear_List = CAssistanceYearList.Trim();
                

                new ACNCRepository().GetDisabilityAssistance(out CountDisabilityAssistance, out DAssistanceYearList);
                ViewBag.CountDisabilityAssistance_List = CountDisabilityAssistance.Trim();
                ViewBag.DAssistanceYear_List = DAssistanceYearList.Trim();

                new ACNCRepository().GetSpokenEnglish(out CountEngSpeak, out EngIssue_Year);
                ViewBag.CountEngSpeak_List = CountEngSpeak.Trim();
                ViewBag.English_Year = EngIssue_Year.Trim();

                new ACNCRepository().GlenEducation(out CountEducation, out Education_Year);
                ViewBag.CountEducation = CountEducation.Trim();
                ViewBag.Education_Year = Education_Year.Trim();

                return View();
            }
            catch (Exception)
            {
                throw;
            }
        }
        public ActionResult test()
        {
            return View();
        }
    }
   
}

Charity/Controllers/DonationController.cs
using BuisnessEntities.Concrete;
using BuisnessEntities.Entities;
using BuisnessEntities.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Charity.Controllers
{
    public class DonationController : BaseController
    {
        public DonationController() : base()
        {

        }
        // GET: Donation
        public ActionResult Donate()
        {
            FilterCriteriaModel searchModel = new FilterCriteriaModel();
            searchModel.PageSize = 10;
            ListModel<ACNCModel> model = new ListModel<ACNCModel>();
            model.PagingResult = new ACNCRepository().GetListOfACNCDetails(searchModel);
            model.FilterCriteriaModel = searchModel;
            return View(model);
        }
        public ActionResult Category(int Category = 0)
        {
            
                if (Category == 0)
                {
                    ViewBag.Heading = "all the categories";
                }
                if (Category == 1)
                {
                    ViewBag.Heading = "Animals";
                }
                if (Category == 2)
                {
                    ViewBag.Heading = "Environment";
                }
                if (Category == 3)
                {
                    ViewBag.Heading = "Disability";
                }
                if (Category == 4)
                {
                    ViewBag.Heading = "Religion";
                }
                if (Category == 5)
                {
                    ViewBag.Heading = "Aged People";
                }
                if (Category == 6)
                {
                    ViewBag.Heading = "Social and Public welfare";
                }
                if (Category == 7)
                {
                    ViewBag.Heading = "Health";
                }
                if (Category == 8)
                {
                    ViewBag.Heading = "Education";
                }
                if (Category == 9)
                {
                    ViewBag.Heading = "Homeless People";
                }
                if (Category == 10)
                {
                    ViewBag.Heading = "Childcare";
                }
                FilterCriteriaModel searchModel = new FilterCriteriaModel();
                searchModel.PageSize = 6;
                searchModel.categoryid = Category;
                ListModel<ACNCModel> model = new ListModel<ACNCModel>();
                model.PagingResult = new ACNCRepository().GetCategoryData(searchModel);
                model.FilterCriteriaModel = searchModel;
                return View(model);
           
           
        }
        public ActionResult SearchResult()
        {

            FilterCriteriaModel searchModel = new FilterCriteriaModel();
            searchModel.PageSize = 10;
            
            ListModel<ACNCModel> model = new ListModel<ACNCModel>();
            model.PagingResult = new ACNCRepository().GetCategoryData(searchModel);
            model.FilterCriteriaModel = searchModel;
            return View(model);
        }

        public ActionResult GetACNCDetails(FilterCriteriaModel model)
        {
            var result = new ACNCRepository().GetCategoryData(model);
            string view = RenderRazorViewToString("_LoadResultTest", result.DataList);
            result.Data = view;
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Resultpage()
        {
            return View();
        }

        public ActionResult CharityInfo(string ABN)
        {
           ResultModel model= new ACNCRepository().GetCharityInfo(ABN);
           return View("Resultpage",model);
        }
    }
}

Charity/Views/Shared/_CareFor.cshtml
@model List<SelectListItem>
@Html.DropDownList("CareForSelect", Model.ToList(), new { @onchange = "GetHelpFor()" })

Charity/Views/Shared/_Facilities.cshtml
@model List<SelectListItem>
@Html.DropDownList("FacilitiesForSelect", Model.ToList())

Charity/Views/Shared/_HelpForData.cshtml
@model List<SelectListItem>
@Html.DropDownList("HelpForSelect", Model.ToList(),new { @onchange = "GetFaciltities()" })

Charity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Real Heroes</title>



    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Dosis:400,700' rel='stylesheet' type='text/css'>
    <link href="/Content/paging.css" rel="stylesheet" />
    <!-- Bootsrap -->
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <!-- Font awesome -->
    <link rel="stylesheet" href="~/assets/css/font-awesome.min.css">
    <!-- Owl carousel -->
    <link rel="stylesheet" href="~/assets/css/owl.carousel.css">
    <!-- Template main Css -->
    <link rel="stylesheet" href="~/assets/css/main.css">

    <!-- Modernizr -->
    <script src="~/assets/js/modernizr-2.6.2.min.js"></script>
    <style>
        .logo-new {
            font-family: "Dosis", sans-serif;
            font-weight: 600;
            vertical-align: top;
            line-height: 32px;
            font-size: 25px;
        }
    </style>
</head>
<body>

    <header class="main-header">
        <nav class="navbar navbar-static-top">
           
            <div class="navbar-main">

                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                        <a class="navbar-brand" href="@Url.Action("Index","Home")"><i class="fa fa-handshake-o" style="margin-right: 15px;font-size:35px;" aria-hidden="true"></i><span class="logo-new">REAL HEROES</span></a>

                    </div>
                    <div id="navbar" class="navbar-collapse collapse pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="/Home/Index">HOME</a></li>
                            <li><a href="@Url.Action("Donate","Donation")">CONTRIBUTE</a></li>
                            <li><a href="@Url.Action("IssuesInGE","ACNC")">LOCAL OPPORTUNITIES</a></li>
                            <li><a href="@Url.Action("About","Home")">ABOUT US</a></li>
                            @*<li class="has-child">
                                <a href="#">CAUSES</a>
                                <ul class="submenu">
                                    <li class="submenu-item"><a href="causes.html">Causes list </a></li>
                                    <li class="submenu-item"><a href="causes-single.html">Single cause </a></li>
                                    <li class="submenu-item"><a href="causes-single.html">Single cause </a></li>
                                    <li class="submenu-item"><a href="causes-single.html">Single cause </a></li>
                                </ul>
                            </li>*@
                            @*<li><a href="javascript:void(0);">GALLERY</a></li>
                            <li><a href="javascript:void(0);">CONTACT</a></li>*@
                        </ul>
                    </div>
                </div>

            </div>

        </nav>
    </header> 


    <div class="container body-content" style="padding-bottom: 20px;">
        @RenderBody()
    </div>


    <footer class="main-footer">
        <div class="footer-top">

        </div>

        <div class="footer-main" style="background: #115c9b;">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-4"></div>
                    <div >
                        <ul class="nav navbar-nav">
                            <li><a href="@Url.Action("Index","Home")">HOME</a></li>
                            <li><a href="@Url.Action("Donate","Donation")">DONATE</a></li>
                            <li><a href="@Url.Action("IssuesInGE","ACNC")">VOLUNTEER</a></li>
                            <li><a href="@Url.Action("About","Home")">ABOUT US</a></li>
                          </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="footer-col">
                            @*<h4 class="footer-title">About us <span class="title-under"></span></h4>*@
                            <div class="footer-content">
                                <p style="text-align: center;">
                                    Our special thanks to ACNC for providing data under licence of Creative Commons Attribution 3.0 Australia.
                                </p>
                                <p style="text-align: center;">© RealHeroes Incorporated 2018</p>
                            </div>

                        </div>
                    </div>
                   
                    <div class="clearfix"></div>

                </div>
             


            </div>

        </div>
        @*<div class="footer-bottom">
            <div class="container text-right">
                REAL-HEROES copyrights 2015 - by <a href="#" target="_blank">Ouarmedia</a>
            </div>
        </div>*@

    </footer>
    <!-- Donate Modal -->
    <div class="modal fade" id="donateModal" tabindex="-1" role="dialog" aria-labelledby="donateModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="donateModalLabel">DONATE NOW</h4>
                </div>
                <div class="modal-body">
                    <form class="form-donation">
                        <h3 class="title-style-1 text-center">Thank you for your donation <span class="title-under"></span>  </h3>
                        <div class="row">
                            <div class="form-group col-md-12 ">
                                <input type="text" class="form-control" id="amount" placeholder="AMOUNT(€)">
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-6">
                                <input type="text" class="form-control" name="firstName" placeholder="First name*">
                            </div>
                            <div class="form-group col-md-6">
                                <input type="text" class="form-control" name="lastName" placeholder="Last name*">
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-6">
                                <input type="text" class="form-control" name="email" placeholder="Email*">
                            </div>
                            <div class="form-group col-md-6">
                                <input type="text" class="form-control" name="phone" placeholder="Phone">
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-12">
                                <input type="text" class="form-control" name="address" placeholder="Address">
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-12">
                                <textarea cols="30" rows="4" class="form-control" name="note" placeholder="Additional note"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-12">
                                <button type="submit" class="btn btn-primary pull-right" name="donateNow">DONATE NOW</button>
                            </div>
                        </div>



                    </form>

                </div>
            </div>
        </div>
    </div> <!-- /.modal -->


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/selectjs")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery.form.js"></script>
    <script src="/Scripts/UserDefinedScripts/Common.js"></script>
    <script src="/Scripts/UserDefinedScripts/paging.js"></script>
    <script src="~/Scripts/sliderengine/amazingslider.js"></script>
    <script src="~/Scripts/sliderengine/initslider-1.js"></script>


    @RenderSection("scripts", required: false)

    <!--  Scripts
    ================================================== -->
    <!-- jQuery -->
    <script>window.jQuery || document.write('<script src="~/assets/js/jquery-1.11.1.min.js"><\/script>')</script>
    <!-- Bootsrap javascript file -->
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script>
        $(function () {
            var current = location.pathname;
            if (current == '/')
                current="/Home/Index"
            $('.nav li a').each(function () {
                var $this = $(this);
                // if the current path is like this link, make it active
                if ($this.attr('href').indexOf(current) !== -1) {
                    $this.addClass('is-active');
                }
            })
        })
    </script>
    <!-- owl carouseljavascript file -->
    <script src="~/assets/js/owl.carousel.min.js"></script>
    <!-- Template main javascript -->
    <script src="~/assets/js/main.js"></script>
</body>
</html>

Charity/Views/Shared/_LoadResultTest.cshtml
    @{
        int cols = 3;
        int rows = 0;
        int colWidth = 12 / cols;
        string lastBlock = "</div> <div class='row'>";
    }

@*<link href="~/Scripts/cn/general.css" rel="stylesheet" />
<link href="~/Scripts/cn/responsive.css" rel="stylesheet" />*@
@*<link href="~/Scripts/cn/style.css" rel="stylesheet" />*@
<style>
    .Topic {
        font-size: 15px;
        font-weight: 600;
    }
    .about-us-col .col-details {
        text-align: -webkit-auto;
    }
    .anchorBtn {
        background-color: #108a93;
        color: #eee !important;
        display: block;
        width: 18em;
        padding: 0.5em;
        line-height: 1.4;
        /* background-color: #94B8E9; */
        /* border: 1px solid black; */
        color: #eee;
        text-decoration: none;
        text-align: center;
    }

    .search-tr {
        box-shadow: 0px 3px 3px -2px rgba(0,0,0,0.2), 0px 3px 4px 0px rgba(0,0,0,0.14), 0px 1px 12px 0px rgba(0,0,0,0.19);
        border-radius: 5px;
    }

    .xyz {
        padding-left: 10px;
        padding-top: 10px;
        padding-right: 10px;
        padding-bottom: 10px;
        margin: 0px;
        /* background-image: url(https://d20umu42aunjpx.cloudfront.net/_gfx_/background/search_list_back.jpg); */
        background-repeat: repeat-x;
        background-position: bottom;
    }

    div.xyz h3 {
        padding: 0px;
        font-size: 1.4em;
        margin-bottom: 10px;
        margin-left: 0px;
        font-weight: bold;
    }
</style>

<div class="section-home">

    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-@colWidth col-sm-@(colWidth*2)" style="margin-bottom:15px;">
                <div class="about-us-col" style="height:400px !important">
                            <h3 class="col-title"><a href="@Url.Action("CharityInfo","Donation",new { ABN= item.ABN })" style="font-weight: bold;">@item.CharityName</a></h3>
                            <div class="col-details">

                                <span class="Topic">LOCATION: </span> @item.Address @item.Suburb <br />
                                @*<span class="Topic">Main Activity: </span> @item.Activity<br />*@
                                <span class="Topic">Contact Number: </span>
                                @if (item.Contact != null)
                                {
                                        <span>@item.Contact </span> 
                                }
                                else
                                {
                                    <span>Not Available</span>
                                } 
                                <br />
                                <span class="Topic">Average no. of Volunteer working: </span>: @item.Volunteer
                            </div>
                    <div class="form-group">
                        <a href="@Url.Action("CharityInfo","Donation",new { ABN= item.ABN })" class="btn btn-primary" style="width:100%;">Click To Find Out More</a>
                    </div>
                    <div class="form-group">
                        @if (item.Website != null)
                        {
                            if (item.Website.StartsWith("http://") == true)
                            {
                                <a target="_blank" href="@item.Website" class="btn btn-primary" style="width:100%;">Visit Charity Website</a>
                            }
                            else if (item.Website.StartsWith("https://") == true)
                            {
                                <a target="_blank" href="@item.Website" class="btn btn-primary" style="width:100%;">Visit Charity Website</a>
                            }
                            else if (item.Website.StartsWith("http://") == false || item.Website.StartsWith("https://") == false || item.Website.StartsWith("https//") == false)
                            {
                                item.Website = "http://" + item.Website;
                                <a target="_blank" href="@item.Website" class="btn btn-primary" style="width:100%;">Visit Charity Website</a>
                            }
                        }
                        <br/>
                        
                    </div>
                   
                    
                 </div>
            </div>
            rows++;
            
        }
    </div>
 </div>


                   
                    <div class="clear"></div>
<style>
    .about-us-col .col-details{
        min-height: 155px !important;
    }
</style>

Charity/Views/Shared/_LoadResults.cshtml
@using BuisnessEntities.Entities
@using System.Linq
@model List<ACNCModel>

    @if (!Model.Any())
    {

        <p>Looks like there was no result for your given search. Sorry about that.</p>
        <p>Please try again with different serach keyword</p>
    }
    else
    {
    <table class="charitytable">
        <thead>
            <tr>
                <th id="Name">Charity Name</th>
                <th class="revenue tooltipd" id="Address">Address</th>
                <th class="staff tooltipd" id="Suburb">Town City</th>
                <th class="transparency tooltipd" id="CharitySize">Charity Size</th>
                <th class="finances tooltipd" id="Donate">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="datarow" id="Charity_Record">
                    <td>@item.CharityName</td>
                    <td>@item.Address</td>
                    <td>@item.Town</td>
                    <td>@item.Size</td>
                    <td>@if (item.charityWebsite != null)
                    {
                        if (item.charityWebsite.StartsWith("http://") == false || item.charityWebsite.StartsWith("https://") == false )
                        {
                            item.charityWebsite = "http://" + item.charityWebsite;
                        }
                        <a href="@item.charityWebsite">Website link</a>
                    }
                </tr>
            }
        </tbody>
    </table><br style="clear:both;">
    }

Charity/Views/Shared/_Paging.cshtml
<div class="pagingWrapper">
    <div class="total-results">Total <span class="total-results-count"></span> Results</div>
    <div class="pager">
        <span class="first">« First</span> <span class="previous">Previous</span> <span class="numeric">
        </span><span class="next">Next</span> <span class="last">Last »</span>
    </div>
    <div class="pageInfo">
    </div>
</div>